import localFont from "next/font/local";
import "./globals.css";
import NavbarPage from "@/component/navbar/NavbarPage";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sticky top-0 z-10">
          <NavbarPage></NavbarPage>
        </div>

        <main className="max-w-[1440px] mx-auto px-2">{children}</main>
      </body>
    </html>
  );
}
