import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
// import NavbarPage from "@/component/navbar/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <>
          <NavbarPage></NavbarPage>
        </> */}
        <div className="bg-white">
          <div className="flex py-2 items-center justify-between sticky top-0 z-10 max-w-[1440px] mx-auto px-2">
            <>
              <a className="text-2xl font-bold">
                <span className="text-blue-400">B</span>P
              </a>
            </>
            <div className="flex gap-5">
              <Link
                className="bg-blue-400/20 text-blue-400 font-semibold px-4 py-1 rounded-lg"
                href={"/"}
              >
                Home
              </Link>
              <Link
                className="bg-blue-400/20 text-blue-400 font-semibold px-4 py-1 rounded-lg"
                href={"/profile"}
              >
                Profile
              </Link>
            </div>
            <>
              <button className="bg-blue-400/20 text-blue-400 font-semibold px-4 py-1 rounded-lg">
                Login
              </button>
            </>
          </div>
        </div>

        <main className="max-w-[1440px] mx-auto px-2">{children}</main>
      </body>
    </html>
  );
}
